name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ci:
    name: Format, Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true

      - name: Lint
        run: script/lint

      - name: Test
        run: script/test
